### ISSUE TITLE
Auth Create User via Postman failed

### ISSUE THREAD

**Issue by varit** [varit/waterfall#2]
# PROJECT ISSUE TICKET

## Unexpected Behavior

Unable to create new user

## Expected Behavior

Should be able to create a new user

## Reproduce the Error

```md
1. Clone repo
2. CD into repo
3. Git checkout to dev branch
3. Start server  `rails s`
4. Open Postman, select "POST", type "http://localhost:3000/users"
5. Select "Body" then "raw"
6. Paste the following code block: 
 {
    "user": {
        "username": "Ruby",
        "email": "ruby@email.com",
        "password": "123456"
    }
}

7. Click "Send"
```

## Documentation

```
ActionController::ParameterMissing (param is missing or the value is empty: user
Did you mean?  controller
               action):

app/controllers/users_controller.rb:53:in `user_params'
app/controllers/users_controller.rb:18:in `create'
```

## Attempted Resolution

```md
1. https://git.generalassemb.ly/sei-nyc-ruby/rails-react-auth-bcrypt-lesson
2. https://stackoverflow.com/questions/49793030/actioncontrollerparametermissing-param-is-missing-or-the-value-is-empty-use
```

**Comment by varit** [comment]
Postman issue:
User error - Selected "text" field instead of "JSON", thus unable to POST correctly
